Create scheduled GH Issues creation

diff --git a/ci-resources/adk/llama/vllm/cloudbuild.yaml b/ci-resources/adk/llama/vllm/cloudbuild.yaml
--- a/ci-resources/adk/llama/vllm/cloudbuild.yaml
+++ b/ci-resources/adk/llama/vllm/cloudbuild.yaml
@@ -76,6 +76,46 @@ steps:
   allowFailure: true
   waitFor: ['adk-llama-vllm: create gke cluster']
 
+- id: 'adk-llama-vllm: allocate L4 GPU'
+  name: "gcr.io/cloud-builders/kubectl"
+  env:
+  - "KUBE_LOAD_CONFIG_FILE=false"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    echo "fail" > /workspace/adk_llama_vllm_allocate_l4_gpu_result.txt
+
+    cat <<EOF > /workspace/gpu-l4-allocation.yaml
+    apiVersion: v1
+    kind: Pod
+    metadata:
+      name: my-gpu-pod
+    spec:
+      nodeSelector:
+        cloud.google.com/gke-accelerator: "nvidia-l4"
+      containers:
+      - name: my-gpu-container
+        image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
+        command: ["/bin/bash", "-c", "--"]
+        args: ["while true; do sleep 600; done;"]
+        resources:
+          requests:
+            cpu: "2"
+            memory: "10Gi"
+            nvidia.com/gpu: "1"
+    EOF
+    cat /workspace/gpu-l4-allocation.yaml
+
+    kubectl apply -f /workspace/gpu-l4-allocation.yaml
+    kubectl wait --for=condition=Ready pod/my-gpu-pod --timeout=1200s
+
+    echo "pass" > /workspace/adk_llama_vllm_allocate_l4_gpu_result.txt
+  allowFailure: true
+  waitFor: ['adk-llama-vllm: generate kubeconfig']
+
 - id: "adk-llama-vllm: test guide"
   name: "gcr.io/cloud-builders/kubectl"
   dir: "/workspace/adk/llama/vllm"
@@ -95,6 +135,7 @@ steps:
         --dry-run=client -o yaml | kubectl apply -f -
 
     cd deploy-llm
+    kubectl delete -f /workspace/gpu-l4-allocation.yaml
     kubectl apply -f deploy-llm.yaml
     kubectl rollout status deployment/vllm-llama3-deployment
 
@@ -140,7 +181,7 @@ steps:
 
     echo "pass" > /workspace/adk_llama_vllm_test_guide.txt
   allowFailure: true
-  waitFor: ['adk-llama-vllm: generate kubeconfig', 'adk-llama-vllm: build adk-agent']
+  waitFor: ['adk-llama-vllm: allocate L4 GPU', 'adk-llama-vllm: build adk-agent']
 
 - id: 'adk-llama-vllm: cleanup gke cluster'
   name: "gcr.io/${PROJECT_ID}/terraform"
@@ -163,10 +204,66 @@ steps:
   allowFailure: true
   waitFor: ['adk-llama-vllm: test guide']
 
-- id: 'check result'
+- id: 'adk-llama-vllm: create github issue'
+  name: 'gcr.io/cloud-builders/curl'
+  secretEnv: ["GITHUB_TOKEN"]
+  entrypoint: '/bin/bash'
+  args:
+  - -c
+  - |
+    apt update
+    apt install jq --assume-yes
+
+    echo $_GITHUB_ISSUE
+    if [[ $_GITHUB_ISSUE != "true" || "$(cat /workspace/adk_llama_vllm_allocate_l4_gpu_result.txt)" != "pass" ]]; then
+      exit 0
+    fi
+
+    if curl -L \
+      -H "Accept: application/vnd.github+json" \
+      -H "Authorization: Bearer $$GITHUB_TOKEN" \
+      -H "X-GitHub-Api-Version: 2022-11-28" \
+      https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues | jq -e '.[] | select(.labels[] | .name == "adk-llama-vllm") | select(.labels[] | .name == "ci/automated-issue")' > /dev/null
+    then
+      exit 0
+    fi
+
+    failed_steps=""
+
+    # Read the results from each step's log file
+    if [[ $(cat /workspace/adk_llama_vllm_gke_cluster_result.txt) != "pass" ]]; then
+      failed_steps+="* adk llama vllm gke cluster creation failed\n"
+    fi
+
+    if [[ $(cat /workspace/adk_llama_vllm_test_guide.txt) != "pass" ]]; then
+      failed_steps+="* adk llama vllm test guide failed\n"
+    fi
+
+    if [[ $(cat /workspace/adk_llama_vllm_cleanup_gke_cluster.txt) != "pass" ]]; then
+      failed_steps+="* adk llama vllm gke cluster cleanup failed\n"
+    fi
+
+    # If there are any failed steps, create a GitHub Issue
+    if [[ -n "$failed_steps" ]]; then
+      issue_title="ADK Llama vLLM CI/CD Failure: Some steps have failed"
+      issue_body="The following steps failed in the Cloud Build pipeline:\n\n$failed_steps"
+
+      payload=$(printf '{"title":"%s","body":"%s","labels":["bug", "adk-llama-vllm", "ci/automated-issue"]}' "$issue_title" "$issue_body")
+
+      curl -L \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $$GITHUB_TOKEN" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
+        -d "$payload"
+    fi
+  allowFailure: true
+  waitFor: ['adk-llama-vllm: cleanup gke cluster']
+
+- id: 'adk-llama-vllm: check result'
   name: "ubuntu"
   entrypoint: 'bash'
-  waitFor: ['adk-llama-vllm: cleanup gke cluster']
   args:
   - '-c'
   - |
@@ -193,6 +290,7 @@ steps:
       cat /workspace/check_result.txt
       exit 1
     fi
+  waitFor: ['adk-llama-vllm: create github issue']
 
 substitutions:
   _ADK_LLAMA_VLLM_REGION: us-east4
@@ -208,3 +306,5 @@ availableSecrets:
   secretManager:
   - versionName: projects/ai-on-gke-qss/secrets/cloudbuild-hf-token/versions/latest
     env: "HF_TOKEN"
+  - versionName: projects/ai-on-gke-qss/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest
+    env: "GITHUB_TOKEN"
diff --git a/ci-resources/adk/ray-mcp/cloudbuild.yaml b/ci-resources/adk/ray-mcp/cloudbuild.yaml
--- a/ci-resources/adk/ray-mcp/cloudbuild.yaml
+++ b/ci-resources/adk/ray-mcp/cloudbuild.yaml
@@ -124,6 +124,50 @@ steps:
   allowFailure: true
   waitFor: ['adk-ray-mcp: create gke cluster']
 
+- id: 'ray-serve: allocate L4 GPU'
+  name: "gcr.io/cloud-builders/kubectl"
+  env:
+  - "KUBE_LOAD_CONFIG_FILE=false"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    echo "fail" > /workspace/adk_ray_mcp_allocate_l4_gpu_result.txt
+
+    cat <<EOF > /workspace/gpu-l4-allocation.yaml
+    apiVersion: v1
+    kind: Pod
+    metadata:
+      name: my-gpu-pod
+    spec:
+      nodeSelector:
+        cloud.google.com/gke-accelerator: "nvidia-l4"
+      containers:
+      - name: my-gpu-container
+        image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
+        command: ["/bin/bash", "-c", "--"]
+        args: ["while true; do sleep 600; done;"]
+        resources:
+          limits:
+            cpu: "8"
+            memory: "16Gi"
+            nvidia.com/gpu: "1"
+          requests:
+            cpu: "8"
+            memory: "16Gi"
+            nvidia.com/gpu: "1"
+    EOF
+    cat /workspace/gpu-l4-allocation.yaml
+
+    kubectl apply -f /workspace/gpu-l4-allocation.yaml
+    kubectl wait --for=condition=Ready pod/my-gpu-pod --timeout=1200s
+
+    echo "pass" > /workspace/adk_ray_mcp_allocate_l4_gpu_result.txt
+  allowFailure: true
+  waitFor: ['adk-ray-mcp: generate kubeconfig']
+
 - id: "adk-ray-mcp: test kuberay"
   name: "gcr.io/cloud-builders/kubectl"
   dir: "/workspace/ray-serve/ray-serve-vllm"
@@ -147,10 +191,11 @@ steps:
     sed -i "s|image: us-docker.pkg.dev/<PROJECT-ID>/llama-ray/llama-ray-serve:latest|image: us-docker.pkg.dev/${PROJECT_ID}/ml-adk-ray-mcp-${_BUILD_ID}-${_AUTOPILOT_CLUSTER}/llama-ray-serve:latest|g" ray-service.yaml
     sed -i "s|serviceAccount: adk-ray-agent-sa|serviceAccount: ml-adk-ray-mcp-${_BUILD_ID}-${_AUTOPILOT_CLUSTER}-sa|g" ray-service.yaml
     cat ray-service.yaml
+    kubectl delete -f /workspace/gpu-l4-allocation.yaml
     kubectl apply -f ray-service.yaml
 
     sleep 30s
-    kubectl wait --for=jsonpath='.status.conditions[0].status'=True rayservice/llama-31-8b --timeout=1200s
+    kubectl wait --for=jsonpath='.status.conditions[0].status'=True rayservice/llama-31-8b --timeout=2400s
     kubectl get rayservice llama-31-8b -o yaml
 
     sleep_seconds=30
@@ -167,7 +212,7 @@ steps:
 
     echo "pass" > /workspace/adk_ray_mcp_deploy_ray-serve.txt
   allowFailure: true
-  waitFor: ['adk-ray-mcp: install kuberay-operator', 'adk-ray-mcp: build ray-serve-vllm', 'adk-ray-mcp: build mcp-server', 'adk-ray-mcp: build adk-agent']
+  waitFor: ['adk-ray-mcp: install kuberay-operator', 'adk-ray-mcp: build ray-serve-vllm', 'adk-ray-mcp: build mcp-server', 'adk-ray-mcp: build adk-agent', 'ray-serve: allocate L4 GPU']
 
 - id: "adk-ray-mcp: test adk"
   name: "gcr.io/cloud-builders/kubectl"
@@ -236,7 +281,68 @@ steps:
   allowFailure: true
   waitFor: ['adk-ray-mcp: test adk']
 
-- id: 'check result'
+- id: 'adk-ray-mcp: create github issue'
+  name: 'gcr.io/cloud-builders/curl'
+  secretEnv: ["GITHUB_TOKEN"]
+  entrypoint: '/bin/bash'
+  args:
+  - -c
+  - |
+    apt update
+    apt install jq --assume-yes
+
+    echo $_GITHUB_ISSUE
+    if [[ $_GITHUB_ISSUE != "true" || "$(cat /workspace/adk_ray_mcp_allocate_l4_gpu_result.txt)" != "pass" ]]; then
+      exit 0
+    fi
+
+    if curl -L \
+      -H "Accept: application/vnd.github+json" \
+      -H "Authorization: Bearer $$GITHUB_TOKEN" \
+      -H "X-GitHub-Api-Version: 2022-11-28" \
+      https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues | jq -e '.[] | select(.labels[] | .name == "adk-ray-mcp") | select(.labels[] | .name == "ci/automated-issue")' > /dev/null
+    then
+      exit 0
+    fi
+
+    failed_steps=""
+
+    # Read the results from each step's log file
+    if [[ $(cat /workspace/adk_ray_mcp_gke_cluster_result.txt) != "pass" ]]; then
+      failed_steps+="* adk-ray-mcp gke cluster creation failed\n"
+    fi
+
+    if [[ $(cat /workspace/adk_ray_mcp_deploy_ray-serve.txt) != "pass" ]]; then
+      failed_steps+="* adk-ray-mcp deploy ray-serve failed\n"
+    fi
+
+    if [[ $(cat /workspace/adk_ray_mcp_test_guide.txt) != "pass" ]]; then
+      failed_steps+="* adk-ray-mcp test guide failed\n"
+    fi
+
+    if [[ $(cat /workspace/adk_ray_mcp_cleanup_gke_cluster.txt) != "pass" ]]; then
+      failed_steps+="* adk-ray-mcp gke cluster cleanup failed\n"
+    fi
+
+    # If there are any failed steps, create a GitHub Issue
+    if [[ -n "$failed_steps" ]]; then
+      issue_title="ADK Ray-MCP CI/CD Failure: Some steps have failed"
+      issue_body="The following steps failed in the Cloud Build pipeline:\n\n$failed_steps"
+
+      payload=$(printf '{"title":"%s","body":"%s","labels":["bug", "adk-ray-mcp", "ci/automated-issue"]}' "$issue_title" "$issue_body")
+
+      curl -L \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $$GITHUB_TOKEN" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
+        -d "$payload"
+    fi
+  allowFailure: true
+  waitFor: ['adk-ray-mcp: cleanup gke cluster']
+
+- id: 'adk-ray-mcp: check result'
   name: "ubuntu"
   entrypoint: 'bash'
   args:
@@ -256,13 +362,14 @@ steps:
       echo "error" > /workspace/check_result.txt
     fi
 
-    if [[ $(cat /workspace/adk_ray_mcp_cleanup_gke_cluster.txt) != "pass" ]]; then
-      echo "adk-ray-mcp gke cluster cleanup failed"
-      echo "error" > /workspace/check_result.txt
-    fi
 
     if [[ $(cat /workspace/adk_ray_mcp_test_guide.txt) != "pass" ]]; then
       echo "adk-ray-mcp test guide failed"
+      echo "error" > /workspace/check_result.txt
+    fi
+
+    if [[ $(cat /workspace/adk_ray_mcp_cleanup_gke_cluster.txt) != "pass" ]]; then
+      echo "adk-ray-mcp gke cluster cleanup failed"
       echo "error" > /workspace/check_result.txt
     fi
 
@@ -270,7 +377,7 @@ steps:
       cat /workspace/check_result.txt
       exit 1
     fi
-  waitFor: ['adk-ray-mcp: cleanup gke cluster']
+  waitFor: ['adk-ray-mcp: create github issue']
 
 substitutions:
   _RAY_SERVE_REGION: us-central1
@@ -286,3 +393,5 @@ availableSecrets:
   secretManager:
   - versionName: projects/ai-on-gke-qss/secrets/cloudbuild-hf-token/versions/latest
     env: "HF_TOKEN"
+  - versionName: projects/ai-on-gke-qss/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest
+    env: "GITHUB_TOKEN"
diff --git a/ci-resources/flowise/cloudbuild.yaml b/ci-resources/flowise/cloudbuild.yaml
--- a/ci-resources/flowise/cloudbuild.yaml
+++ b/ci-resources/flowise/cloudbuild.yaml
@@ -65,6 +65,46 @@ steps:
   allowFailure: true
   waitFor: ['flowise: create gke cluster']
 
+- id: 'flowise: allocate L4 GPU'
+  name: "gcr.io/cloud-builders/kubectl"
+  env:
+  - "KUBE_LOAD_CONFIG_FILE=false"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    echo "fail" > /workspace/flowise_allocate_l4_gpu_result.txt
+
+    cat <<EOF > /workspace/gpu-l4-allocation.yaml
+    apiVersion: v1
+    kind: Pod
+    metadata:
+      name: my-gpu-pod
+    spec:
+      nodeSelector:
+        cloud.google.com/gke-accelerator: "nvidia-l4"
+      containers:
+      - name: my-gpu-container
+        image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
+        command: ["/bin/bash", "-c", "--"]
+        args: ["while true; do sleep 600; done;"]
+        resources:
+          limits:
+            cpu: 2
+            memory: 4Gi
+            nvidia.com/gpu: 1
+    EOF
+    cat /workspace/gpu-l4-allocation.yaml
+
+    kubectl apply -f /workspace/gpu-l4-allocation.yaml
+    kubectl wait --for=condition=Ready pod/my-gpu-pod --timeout=1200s
+
+    echo "pass" > /workspace/flowise_allocate_l4_gpu_result.txt
+  allowFailure: true
+  waitFor: ['flowise: generate kubeconfig']
+
 - id: "flowise: prepare ollama"
   name: "gcr.io/${PROJECT_ID}/terraform"
   dir: "/workspace/flowise/terraform"
@@ -98,6 +138,8 @@ steps:
                   mountPath: /root/.ollama/
               resources:
                 limits:
+                  cpu: 2
+                  memory: 4Gi
                   nvidia.com/gpu: 1
           volumes:
             - name: ollama-data
@@ -120,7 +162,7 @@ steps:
           targetPort: 11434
     EOF
     cat ../ollama-deployment.yml
-  waitFor: ["flowise: generate kubeconfig"]
+  waitFor: ["flowise: create gke cluster"]
 
 - id: 'flowise: deploy ollama'
   name: "gcr.io/cloud-builders/kubectl"
@@ -136,6 +178,7 @@ steps:
     echo "fail" > /workspace/flowise_deploy_ollama_result.txt
 
     echo ../ollama-deployment.yml
+    kubectl delete -f /workspace/gpu-l4-allocation.yaml
     kubectl apply -f ../ollama-deployment.yml
     kubectl rollout status deployment/ollama
     sleep 60s
@@ -143,7 +186,7 @@ steps:
 
     echo "pass" > /workspace/flowise_deploy_ollama_result.txt
   allowFailure: true
-  waitFor: ['flowise: prepare ollama']
+  waitFor: ['flowise: allocate L4 GPU', 'flowise: prepare ollama']
 
 - id: "flowise: prepare flowise helm chart"
   name: "gcr.io/${PROJECT_ID}/terraform"
@@ -262,10 +305,71 @@ steps:
   allowFailure: true
   waitFor: ['flowise: test guide']
 
-- id: 'check result'
+- id: 'flowise: create github issue'
+  name: 'gcr.io/cloud-builders/curl'
+  secretEnv: ["GITHUB_TOKEN"]
+  entrypoint: '/bin/bash'
+  args:
+  - -c
+  - |
+    apt update
+    apt install jq --assume-yes
+
+    echo $_GITHUB_ISSUE
+
+    if [[ "$_GITHUB_ISSUE" != "true" || "$(cat /workspace/flowise_allocate_l4_gpu_result.txt)" != "pass" ]]; then
+      exit 0
+    fi
+
+    if curl -L \
+      -H "Accept: application/vnd.github+json" \
+      -H "Authorization: Bearer $$GITHUB_TOKEN" \
+      -H "X-GitHub-Api-Version: 2022-11-28" \
+      https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues | jq -e '.[] | select(.labels[] | .name == "flowise") | select(.labels[] | .name == "ci/automated-issue")' > /dev/null
+    then
+      exit 0
+    fi
+
+    failed_steps=""
+
+    # Read the results from each step's log file
+    if [[ $(cat /workspace/flowise_gke_cluster_result.txt) != "pass" ]]; then
+      failed_steps+="* flowise gke cluster creation failed\n"
+    fi
+
+    if [[ $(cat /workspace/flowise_deploy_ollama_result.txt) != "pass" ]]; then
+      failed_steps+="* flowise deploy ollama failed\n"
+    fi
+
+    if [[ $(cat /workspace/flowise_test_guide_result.txt) != "pass" ]]; then
+      failed_steps+="* flowise test guide failed\n"
+    fi
+
+    if [[ $(cat /workspace/flowise_cleanup_gke_cluster.txt) != "pass" ]]; then
+      failed_steps+="* flowise gke cluster cleanup failed\n"
+    fi
+
+    # If there are any failed steps, create a GitHub Issue
+    if [[ -n "$failed_steps" ]]; then
+      issue_title="Flowise CI/CD Failure: Some steps have failed"
+      issue_body="The following steps failed in the Cloud Build pipeline:\n\n$failed_steps"
+
+      payload=$(printf '{"title":"%s","body":"%s","labels":["bug", "flowise", "ci/automated-issue"]}' "$issue_title" "$issue_body")
+
+      curl -L \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $$GITHUB_TOKEN" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
+        -d "$payload"
+    fi
+  allowFailure: true
+  waitFor: ['flowise: cleanup gke cluster']
+
+- id: 'flowise: check result'
   name: "ubuntu"
   entrypoint: 'bash'
-  waitFor: ['flowise: cleanup gke cluster']
   args:
   - '-c'
   - |
@@ -297,6 +401,7 @@ steps:
       cat /workspace/check_result.txt
       exit 1
     fi
+  waitFor: ['flowise: create github issue']
 
 substitutions:
   _FLOWISE_REGION: us-central1
@@ -308,3 +413,7 @@ options:
   substitutionOption: "ALLOW_LOOSE"
   machineType: "E2_HIGHCPU_8"
 timeout: 5400s
+availableSecrets:
+  secretManager:
+  - versionName: projects/ai-on-gke-qss/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest
+    env: "GITHUB_TOKEN"
diff --git a/ci-resources/ray-serve/cloudbuild.yaml b/ci-resources/ray-serve/cloudbuild.yaml
--- a/ci-resources/ray-serve/cloudbuild.yaml
+++ b/ci-resources/ray-serve/cloudbuild.yaml
@@ -110,6 +110,50 @@ steps:
   allowFailure: true
   waitFor: ['ray-serve: create gke cluster']
 
+- id: 'ray-serve: allocate L4 GPU'
+  name: "gcr.io/cloud-builders/kubectl"
+  env:
+  - "KUBE_LOAD_CONFIG_FILE=false"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    echo "fail" > /workspace/ray_serve_allocate_l4_gpu_result.txt
+
+    cat <<EOF > /workspace/gpu-l4-allocation.yaml
+    apiVersion: v1
+    kind: Pod
+    metadata:
+      name: my-gpu-pod
+    spec:
+      nodeSelector:
+        cloud.google.com/gke-accelerator: "nvidia-l4"
+      containers:
+      - name: my-gpu-container
+        image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
+        command: ["/bin/bash", "-c", "--"]
+        args: ["while true; do sleep 600; done;"]
+        resources:
+          limits:
+            cpu: "8"
+            memory: "16Gi"
+            nvidia.com/gpu: "1"
+          requests:
+            cpu: "8"
+            memory: "16Gi"
+            nvidia.com/gpu: "1"
+    EOF
+    cat /workspace/gpu-l4-allocation.yaml
+
+    kubectl apply -f /workspace/gpu-l4-allocation.yaml
+    kubectl wait --for=condition=Ready pod/my-gpu-pod --timeout=1200s
+
+    echo "pass" > /workspace/ray_serve_allocate_l4_gpu_result.txt
+  allowFailure: true
+  waitFor: ['ray-serve: generate kubeconfig']
+
 - id: "ray-serve: test guide"
   name: "gcr.io/cloud-builders/kubectl"
   dir: "/workspace/ray-serve/ray-serve-vllm"
@@ -133,10 +177,11 @@ steps:
     sed -i "s|image: us-docker.pkg.dev/<PROJECT-ID>/llama-ray/llama-ray-serve:latest|image: us-docker.pkg.dev/${PROJECT_ID}/ml-ray-serve-${_BUILD_ID}-${_AUTOPILOT_CLUSTER}/llama-ray-serve:latest|g" ray-service.yaml
     sed -i "s|serviceAccount: adk-ray-agent-sa|serviceAccount: ml-ray-serve-${_BUILD_ID}-${_AUTOPILOT_CLUSTER}-sa|g" ray-service.yaml
     cat ray-service.yaml
+    kubectl delete -f /workspace/gpu-l4-allocation.yaml
     kubectl apply -f ray-service.yaml
 
     sleep 30s
-    kubectl wait --for=jsonpath='.status.conditions[0].status'=True rayservice/llama-31-8b --timeout=1200s
+    kubectl wait --for=jsonpath='.status.conditions[0].status'=True rayservice/llama-31-8b --timeout=2400s
     kubectl get rayservice llama-31-8b -o yaml
 
     sleep_seconds=30
@@ -189,7 +234,7 @@ steps:
 
     echo "pass" > /workspace/ray_serve_test_guide.txt
   allowFailure: true
-  waitFor: ['ray-serve: install kuberay-operator', 'ray-serve: build ray-serve-vllm', 'ray-serve: build adk_agent']
+  waitFor: ['ray-serve: install kuberay-operator', 'ray-serve: build ray-serve-vllm', 'ray-serve: build adk_agent', 'ray-serve: allocate L4 GPU']
 
 - id: 'ray-serve: cleanup gke cluster'
   name: "gcr.io/${PROJECT_ID}/terraform"
@@ -218,10 +263,67 @@ steps:
   allowFailure: true
   waitFor: ['ray-serve: test guide']
 
-- id: 'check result'
+- id: 'ray-serve: create github issue'
+  name: 'gcr.io/cloud-builders/curl'
+  secretEnv: ["GITHUB_TOKEN"]
+  entrypoint: '/bin/bash'
+  args:
+  - -c
+  - |
+
+    apt update
+    apt install jq --assume-yes
+
+    echo $_GITHUB_ISSUE
+    if [[ "$_GITHUB_ISSUE" != "true" || "$(cat /workspace/ray_serve_allocate_l4_gpu_result.txt)" != "pass" ]]; then
+      exit 0
+    fi
+
+    if curl -L \
+      -H "Accept: application/vnd.github+json" \
+      -H "Authorization: Bearer $$GITHUB_TOKEN" \
+      -H "X-GitHub-Api-Version: 2022-11-28" \
+      https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues | jq -e '.[] | select(.labels[] | .name == "ray-serve") | select(.labels[] | .name == "ci/automated-issue")' > /dev/null
+    then
+      exit 0
+    fi
+
+    failed_steps=""
+
+    # Read the results from each step's log file
+    if [[ $(cat /workspace/ray_serve_gke_cluster_result.txt) != "pass" ]]; then
+      failed_steps+="* ray-serve gke cluster creation failed\n"
+    fi
+
+    if [[ $(cat /workspace/ray_serve_test_guide.txt) != "pass" ]]; then
+      failed_steps+="* ray-serve test guide failed\n"
+    fi
+
+    if [[ $(cat /workspace/ray_serve_cleanup_gke_cluster.txt) != "pass" ]]; then
+      failed_steps+="* ray-serve gke cluster cleanup failed\n"
+    fi
+
+    # If there are any failed steps, create a GitHub Issue
+    if [[ -n "$failed_steps" ]]; then
+      issue_title="Ray-serve CI/CD Failure: Some steps have failed"
+      issue_body="The following steps failed in the Cloud Build pipeline:\n\n$failed_steps"
+
+      payload=$(printf '{"title":"%s","body":"%s","labels":["bug", "ray-serve", "ci/automated-issue"]}' "$issue_title" "$issue_body")
+
+      curl -L \
+        -X POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $$GITHUB_TOKEN" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
+        -d "$payload"
+    fi
+  allowFailure: true
+  waitFor: ['ray-serve: cleanup gke cluster']
+
+- id: 'ray-serve: check result'
   name: "ubuntu"
   entrypoint: 'bash'
-  waitFor: ['ray-serve: cleanup gke cluster']
   args:
   - '-c'
   - |
@@ -248,6 +350,7 @@ steps:
       cat /workspace/check_result.txt
       exit 1
     fi
+  waitFor: ['ray-serve: create github issue']
 
 substitutions:
   _RAY_SERVE_REGION: us-central1
@@ -263,3 +366,5 @@ availableSecrets:
   secretManager:
   - versionName: projects/ai-on-gke-qss/secrets/cloudbuild-hf-token/versions/latest
     env: "HF_TOKEN"
+  - versionName: projects/ai-on-gke-qss/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest
+    env: "GITHUB_TOKEN"
